### ISSUE TITLE
Blank page after install

### ISSUE THREAD

**Issue by mmlunjwa** [Doptor-zz/Doptor#103]
I've done the following steps without a problem:
Download or checkout the latest copy of Doptor from here (https://github.com/Doptor/Doptor)
Enter the newly created folder. e.g.: cd Doptor
Install the required dependencies with composer. composer install --no-dev
Copy the checkout folder to your web server

But I only get a blank page when I run localhost/Dopter/pubilc/ or localhost/Doptor

Where am I going wrong?

**Comment by SubodhDahal** [comment]
Post the recent error log from the `storage/logs` folder.

**Comment by mmlunjwa** [comment]
This is the error message i get from storage/logs

[2015-06-18 11:04:23] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Uncaught exception 'InvalidArgumentException' with message 'Database does not exist.' in /home/user1/public_html/test/Doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php:34
Stack trace:
#0 /home/user1/public_html/test/Doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\SQLiteConnector->connect(Array)
#1 /home/user1/public_html/test/Doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#2 /home/user1/public_html/test/Doptor/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(177): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'sqlite')
#3 /home/user1/public_html/test/Doptor/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection('sqlite')
#4 /home/user1/public_html/te' in /home/mthabisi/public_html/test/Doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php:34
Stack trace:
#0 {main}

**Comment by SubodhDahal** [comment]
The `production.sqlite` file that should have been inside `database` was previously ignored by git, that's why the problem is occurring. I have already sent a pull request to fix this. If you create a blank `production.sqlite` file inside the `database` folder, your problem should be solved.

**Comment by mmlunjwa** [comment]
Thank you very much, Its now working :-)

**Comment by wexford0709** [comment]
I get
[Fri Aug 28 10:58:40 2015] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Users/wexford0709/Documents/htdocs/doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /Users/wexford0709/Documents/htdocs/doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/wexford0709/Documents/htdocs/doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /Users/wexford0709/Documents/htdocs/doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /Users/wexford0709/Documents/htdocs/doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory-> in /Users/wexford0709/Documents/htdocs/doptor/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php on line 47

Can you help me?
