### ISSUE TITLE
can't add page due to missing language information

### ISSUE THREAD

**Issue by Remo** [Doptor-zz/Doptor#11]
I just installed doptor, including the sample data, but when I'm adding a new page, I get this error:

```
Illuminate \ Database \ QueryException
SQLSTATE[HY000]: General error: 1364 Field 'language_id' doesn't have a default value (SQL: insert into `posts` (`type`, `title`, `permalink`, `content`, `target`, `status`, `publish_start`, `publish_end`, `meta_description`, `meta_keywords`, `featured`, `created_by`) values (page, dsgf, dsgf, <p><strong>dsg</strong></p> <p>sdgdsgf</p> , public, published, , , , , , 15))
```

I'm sure I'll figure out what to do, but you might want to improve the exception handling there.

**Comment by Doptor-zz** [comment]
Thank you Remo, 
Your contribution is much more appreciated. 
We are in heavy pressure, pls feel free pull request. 
Tq
Doptor team

**Comment by ajayphp** [comment]
Hi,

Its nice approach backend and admin section. 
nice work. 

following queries:

-- How to add Hidden, File, Image field in form builder ?

-- Form builder UI need to fix, as form name taken whole screen space
and not able to drag from left to right , have to fix right form fields 

-- how to create relation in modules etc. 
as in module we like to use foreign key of user 
as record related to use, so how to achieve this ?

-- How to create route to achieve module url without Module in  url 
ex: http://site.com/module_name
instead : http://site.com/modules/module_name

-- how can i create scaffold and bind to your crud views
as some times i prefer not to use module builder, rather artisan cli 

-- as your login security, i am not able to login in backend and admin 
at same time , even on different scenario. 
how to override this or disable ?
as backend and admin are different entity , 
and in staff use case also not best approach
and with different username login cause session issue. 

-- How can i add contribute to this repo , could you guide me,
clone this repo and modify and commit -- any branch ref , i never did on github

**Comment by Doptor-zz** [comment]
-- How to add Hidden, File, Image field in form builder ?
N/A.

-- Form builder UI need to fix, as form name taken whole screen space
and not able to drag from left to right , have to fix right form fields
Noted.

-- how to create relation in modules etc. 
as in module we like to use foreign key of user 
as record related to use, so how to achieve this ?
At first pls you create a module with one form including few field.
Second you may create another module with new form including atleast one dropdown. 
during create module in second page select the dropdown source.

-- How to create route to achieve module url without Module in url 
ex: http://site.com/module_name
instead : http://site.com/modules/module_name
N/A

-- how can i create scaffold and bind to your crud views
as some times i prefer not to use module builder, rather artisan cli
N/A

-- as your login security, i am not able to login in backend and admin 
at same time , even on different scenario. 
how to override this or disable ?
as backend and admin are different entity , 
and in staff use case also not best approach
and with different username login cause session issue.
This is our doptor special, everybody can get this facilities. at the same time one user cant login from two pc.

-- How can i add contribute to this repo , could you guide me,
clone this repo and modify and commit -- any branch ref , i never did on github
Know more about github please login www.github.com
