### ISSUE TITLE
unable to change database connection details

### ISSUE THREAD

**Issue by mmlunjwa** [Doptor-zz/Doptor#112]
Unable to change database connection details

I installed doptor on my local machine and it works well. Now I've uploaded it to the live server on a shared hosting and I'm now forced to use a different database name and user password. I've edited config/database.php with the new details but i get an error message showing that i'm still trying to connect with the old username and password. I've cleared the cache and all but i still get the same error.

Is there somewhere else i need to change the details?
Do we only specify the details during the initial installation?

**Comment by Doptor-zz** [comment]
You are advised to change database information at 
/.env.example

**Comment by mmlunjwa** [comment]
The /.env.example has the following settings:
APP_ENV=local
APP_DEBUG=true
APP_KEY=SomeRandomString

DB_HOST=localhost
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null

This is also not my old Db connection details and when I change the settings I still get an error message showing that I'm still trying to connect with the old username and password. I'm not sure where I'm going wrong

**Comment by mmlunjwa** [comment]
I was supposed to edit the 
/.env     instead of the /.env.example
I've got it working now
