### ISSUE TITLE
event handler mappings error

### ISSUE THREAD

**Issue by mmlunjwa** [Doptor-zz/Doptor#113]
ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)' in 
app/Providers/EventServiceProvider.php:21
Stack trace:
#0 {main}

app/Providers/EventServiceProvider.php:21 :
        InstallationWasCompleted::class => [
            DeleteInstaller::class
        ]
What could be causing this error?
I'm getting this after changing Database settings.

**Comment by SubodhDahal** [comment]
The `::class` property is available on PHP 5.5 and above only. That's why the problem is occurring. You need to upgrade to PHP 5.5

Also, you shouldn't post your database configuration from the error log as somebody could use that to compromise your system.

**Comment by mmlunjwa** [comment]
Ok thanks! I'll speak to my ISP about this. On my local machine,  I have PHP version 5.5 and it works well
