### ISSUE TITLE
Login problems after installation

### ISSUE THREAD

**Issue by mambax7** [Doptor-zz/Doptor#115]
I've tried to install it twice locally, and the installation went fine, but when I'me trying to login in both admin and backend, I'm told that my username or password are wrong, and then I am banned for 10 minutes. 
What could be the problem?

**Comment by masud79** [comment]
We couldn't reproduce this issue. Can you provide more details or the error log? Error logs should be at storage/logs folder and the recent error log is the filename with the recent date.
