### ISSUE TITLE
Admin Page Showing error

### ISSUE THREAD

**Issue by lycotech** [Doptor-zz/Doptor#136]
I just install Doptor CMS, the installation was fine and the backend is working fine, but the admin is showing error, what can i do

**Comment by masud79** [comment]
Can you show the error log here? It should be at storage/logs folder and the recent error log is the filename with the recent date.

**Comment by lycotech** [comment]
TIME_ZONE=Africa/Lagos.ERROR: exception 'BadMethodCallException' with message 'Method action does not exist.' in C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:87
Stack trace:

That is the only error i found in the log

**Comment by lycotech** [comment]
[2015-08-20 20:00:15] DB_DATABASE=cms
DB_USERNAME=root
DB_PASSWORD=
DB_HOST=127.0.0.1
DB_TYPE=mysql
TIME_ZONE=Africa/Lagos.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 30 seconds exceeded' in C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Database\Connection.php:296
Stack trace:
#0 {main}  
[2015-08-20 20:01:21] DB_DATABASE=cms
DB_USERNAME=root
DB_PASSWORD=
DB_HOST=127.0.0.1
DB_TYPE=mysql
TIME_ZONE=Africa/Lagos.ERROR: exception 'BadMethodCallException' with message 'Method action does not exist.' in C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php:87
Stack trace:
#0 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(210): Illuminate\Routing\Router->__call('action', Array)
#1 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(210): Illuminate\Routing\Router->action('Backend\HomeCon...')
#2 C:\xampp\htdocs\Doptor\app\Http\routes.php(186): Illuminate\Support\Facades\Facade::__callStatic('action', Array)
#3 C:\xampp\htdocs\Doptor\app\Http\routes.php(186): Illuminate\Support\Facades\Route::action('Backend\HomeCon...')
#4 [internal function]: App\Providers\RouteServiceProvider->{closure}()
#5 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Routing\Route.php(157): call_user_func_array(Object(Closure), Array)
#6 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Routing\Route.php(129): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#7 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Routing\Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\Doptor\app\Http\Middleware\IsStalePassword.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): App\Http\Middleware\IsStalePassword->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 C:\xampp\htdocs\Doptor\app\Http\Middleware\IsAuthorized.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): App\Http\Middleware\IsAuthorized->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\xampp\htdocs\Doptor\app\Http\Middleware\Authenticate.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Routing\Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Routing\Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#20 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\Doptor\app\Http\Middleware\VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 C:\xampp\htdocs\Doptor\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 C:\xampp\htdocs\Doptor\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#42 C:\xampp\htdocs\Doptor\index.php(21): require_once('C:\xampp\htdocs...')
#43 {main}

**Comment by masud79** [comment]
try doing `composer update` again.
