### ISSUE TITLE
Error loading image to a post

### ISSUE THREAD

**Issue by yuri25** [Doptor-zz/Doptor#26]
Intervention \ Image \ Exception \ InvalidArgumentException
resize() accepts only Closure as argument 3.

open: C:\OpenServer\domains\doptor\vendor\intervention\image\src\Intervention\Image\Commands\Argument.php
                break;
        }

```
    if ($fail) {

        $message = isset($message) ? $message : sprintf("Missing argument for %d.", $this->key);

        throw new \Intervention\Image\Exception\InvalidArgumentException(
            $message
        );
```

**Comment by SubodhDahal** [comment]
That error is occurring due to API changes between previous versions of the `Intervention` package and the new one, used for the resizing of image and other image processing operations. As per their upgrade guide: Some methods became redundant, other things have been simplified and therefore had to change.

I have submitted a pull request https://github.com/Doptor/Doptor/pull/29 to solve this problem.

**Comment by CQ2** [comment]
I still have the same problem. I can not insert any image to post or page.

please advice.

**Comment by SubodhDahal** [comment]
View the error log in `app/storage/logs` to get more information about the error.

**Comment by CQ2** [comment]
this is the error message:

exception 'Intervention\Image\Exception\NotWritableException' with message 'Can't write image data to path (uploads/posts/thumbs/Doptor Logo Black.png)' in /Applications/MAMP/htdocs/doptor/vendor/intervention/image/src/Intervention/Image/Image.php:137
Stack trace:
#0 /Applications/MAMP/htdocs/doptor/app/components/posts/models/Post.php(136): Intervention\Image\Image->save('uploads/posts/t...')
#1 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(6854): Post->setImageAttribute('uploads/slidesh...')
#2 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(6003): Illuminate\Database\Eloquent\Model->setAttribute('image', 'uploads/slidesh...')
#3 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(5963): Illuminate\Database\Eloquent\Model->fill(Array)
#4 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(6052): Illuminate\Database\Eloquent\Model->__construct(Array)
#5 /Applications/MAMP/htdocs/doptor/app/components/posts/models/Post.php(53): Illuminate\Database\Eloquent\Model::create(Array)
#6 /Applications/MAMP/htdocs/doptor/app/components/posts/controllers/Backend/PostsController.php(78): Post::create(Array)
#7 [internal function]: Components\Posts\Controllers\Backend\PostsController->store()
#8 /Applications/MAMP/htdocs/doptor/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#9 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(5437): Illuminate\Routing\Controller->callAction('store', Array)
#10 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(5425): Illuminate\Routing\ControllerDispatcher->call(Object(Components\Posts\Controllers\Backend\PostsController), Object(Illuminate\Routing\Route), 'store')
#11 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(4657): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Components\Post...', 'store')
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}()
#13 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(4984): call_user_func_array(Object(Closure), Array)
#14 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(4682): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(4670): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(1146): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(7311): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(7908): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(7855): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(10897): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 /Applications/MAMP/htdocs/doptor/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 /Applications/MAMP/htdocs/doptor/index.php(66): Illuminate\Foundation\Application->run()
#25 {main} [] []

**Comment by CQ2** [comment]
please let me know how can I solve the problem.
