### ISSUE TITLE
Admin and Backend demo

### ISSUE THREAD

**Issue by Mushr0000m** [Doptor-zz/Doptor#27]
Hi !

I want to have a look at your CMS so I went to your demo website but there is no tips on the usernames and passwords for the Admn and Backend parts, can you provides them so we can check the whole CMS.

Thanks a lot !

**Comment by Doptor-zz** [comment]
Pls the same user and password for admin and backend : user: demo, password: demo123

**Comment by Mushr0000m** [comment]
Thanks !

**Comment by CQ2** [comment]
but it is not working with this username and password.

Error!
Invalid username or password

**Comment by codefocus** [comment]
Same here. I was hoping to use Doptor on a client project, but would need to look at the demo before I invest time in this project.

**Comment by Doptor-zz** [comment]
try this
user: demo1
password: demo12345

**Comment by jagankumar16** [comment]
Hi,
Login details which you shared is not working. Can you provide correct login details?

**Comment by Doptor-zz** [comment]
Try now
user: demo1
password: demo12345

**Comment by jagankumar16** [comment]
Thanks. Now its working.
