### ISSUE TITLE
There sure seem to be a lot of similarities to joomla here.

### ISSUE THREAD

**Issue by oasisfleeting** [Doptor-zz/Doptor#37]
Am I crazy when I look at the folder structure, naming conventions, mvc model, and logo and think this is an abstraction of joomla stand alone framework?

**Comment by Doptor-zz** [comment]
Before you create any issue, you should know what is Doptor and joomla. Doptor CMS based on laravel.

**Comment by oasisfleeting** [comment]
Laravel is php :-1:

**Comment by oasisfleeting** [comment]
![joomla_logo 1](https://cloud.githubusercontent.com/assets/1281104/3687265/749b35d4-1324-11e4-83a3-016bcc31007d.png)
And you're ripping Joomla off :-1:

**Comment by Doptor-zz** [comment]
php belongs to joomla owner ? There are 100 + CMS existing based on php, what happen to you ?

**Comment by oasisfleeting** [comment]
<code>Before you create any issue, you should know what is Doptor and joomla. Doptor CMS based on laravel.</code>
Joomla CMS is based on php. Laravel is PHP. Doptor CMS based on php.

**Comment by Doptor-zz** [comment]
So what? Doptor is based on php. Any problem for you ?

**Comment by oasisfleeting** [comment]
You still haven't said whether or not this is an abstraction of Joomla or not.

**Comment by Doptor-zz** [comment]
In this case if you are talking about platform all existing php based CMS are abstraction of Joomla. Not only Doptor.

**Comment by Doptor-zz** [comment]
If you think something else please go ahed. We are here not for argue. Doptor is opensource, helping end user only.

**Comment by Doptor-zz** [comment]
Your contribution for Doptor much more appreciated.
