### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by hofire** [Doptor-zz/Doptor#40]
i install doptor first in my web server, when i open the url: http://www.mydomain.com
i got this error msg:

Error in exception handler: SQLSTATE[HY000]: General error: 1 no such table: menus (SQL: select \* from "menus" where "status" = published and ("publish_start" < 2014-07-24 18:18:15 or "publish_start" = 0000-00-00 00:00:00 or "publish_start" is null) and ("publish_end" > 2014-07-24 18:18:15 or "publish_end" = 0000-00-00 00:00:00 or "publish_end" is null) and ("link" = dp or "link_manual" = dp) and "display_text" <> limit 1) (View: /home/*****_/public_html/web/app/views/public/default/_layouts/_layout.blade.php) (View: /home/hofire.net/public_html/web/app/views/public/default/_layouts/_layout.blade.php) in /home//**_***/public_html/web/vendor/laravel/framework/src/Illuminate/Database/Connection.php:555

how to solve it?
thanks.

**Comment by Doptor-zz** [comment]
Bring this issue at the forum, www.forum.doptor.org

**Comment by Doptor-zz** [comment]
Please install the latest version, we have fix some issue related to sample data.
