### ISSUE TITLE
Add new image

### ISSUE THREAD

**Issue by maydanchi** [Doptor-zz/Doptor#75]
I can not add any image when I try to create new page.
whenever I try to add any image system give me the following error.
500
Oops, Something went wrong.
We are fixing it!
Please come back in a while.

I appreciate your help or suggestion to solve this issue.

regards,

**Comment by SubodhDahal** [comment]
Do you have `php_fileinfo` plugin enabled?

**Comment by CQ2** [comment]
how can I enable it? I can not find following command in my php.ini
I am using Mac and install MAMP...
extension=php_fileinfo.dll

**Comment by CQ2** [comment]
![screen shot 2014-10-21 at 13 42 56](https://cloud.githubusercontent.com/assets/7806955/4718313/d20cc408-591f-11e4-99b6-31cbf1ea5311.png)

![screen shot 2014-10-21 at 13 43 36](https://cloud.githubusercontent.com/assets/7806955/4718321/e9c5fd08-591f-11e4-8ea0-18f1198a4568.png)

it has enabled in css/php.ini

is that the right place??

**Comment by Doptor-zz** [comment]
Fixed.
