### ISSUE TITLE
Doptor Update

### ISSUE THREAD

**Issue by ajayphp** [Doptor-zz/Doptor#82]
Hi, 

I have seen on github there is code updated, 
but when i tried with composer update that only update symphony or others lib,
not the doptor code. 

So how to update the doptor core code, 

-- and please write doc of suggest here how can i attach 
artisian scaffold created (controller,model , views )  as new module in doptor.
Regards,
Thx.

**Comment by masud79** [comment]
`composer update` doesn't update the Doptor CMS. It only updates the packages used. If you've cloned this repository using git then you can do `git pull origin master`, otherwise you need to redownload it as zip and install again.
