### ISSUE TITLE
Could not load package anahkiasen/underscore-php in http://packagist.jp

### ISSUE THREAD

**Issue by verglas** [Doptor-zz/Doptor#92]
Could not load package anahkiasen/underscore-php in http://packagist.org: [U
nexpectedValueException] Could not parse version constraint ^4.2.16: Invali
d version string "^4.2.16"

1，download Doptor-master.zip, uzip.
2，php composer.phar update or php composer.phar install --no-dev
3，fatal error.

ps: The composer was wall(GFW),I use the VPN in South Korea

**Comment by SubodhDahal** [comment]
You need to upgrade your composer first by doing `composer selfupdate` and then after it is completed perform `composer.phar install --no-dev`

**Comment by verglas** [comment]
Thank you, then I have updated the composer, b but when the install error, error information is as follows:

PHP Fatal error: Class 'Illuminate\View\Environment' not found

http://www.keyboardninja.eu/laravel/fix-twigbridge-and-laravel-4-2

I try to add:
"rcrowe/twigbridge": "0.6.*"
Error is still
