### ISSUE TITLE
Failed composer install

### ISSUE THREAD

**Issue by catroot** [Doptor-zz/Doptor#93]
## Have tried to do 

`composer install --no-dev`
got fails to install dependencies

**Comment by patrickcarlohickman** [comment]
The master branch for the [`mews/captcha`](https://github.com/mewebstudio/captcha) package has been updated to require Laravel 5. According to their documentation, the Laravel 4 branch has been moved to `master-l4`. The composer.json file needs to be updated to reflect this (`"mews/captcha": "dev-master-l4"`).
