### ISSUE TITLE
Invalid set of dependencies for Laravel and robclancy/presenter

### ISSUE THREAD

**Issue by patrickcarlohickman** [Doptor-zz/Doptor#94]
The latest [commit](https://github.com/Doptor/Doptor/commit/033f1d8cde0d47e7cbd2dc6f039b4d278c2902cb) left an invalid set of dependencies.

The `robclancy/presenter` package version `1.2.*` requires the `Illuminate/View/Environment.php` file, which is only available up to Laravel 4.1. This file was removed in Laravel 4.2. The `robclancy/presenter` package version `1.3.*` was updated to work with Laravel 4.2.

Therefore, if working with Laravel 4.2, the `robclancy/presenter` package needs version `1.3.*`. If working with Laravel 4.1, the `robclancy/presenter` package needs version `1.2.*`.

Composer install will work fine, but you get a `Class 'Illuminate\View\ Environment' not found` exception during the application install.

**Comment by SubodhDahal** [comment]
The project has been upgraded to Laravel 5. This problem shouldn't occur now.
